# Application Properties:
server:
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${APP_DB_HOST}/${APP_DB_NAME}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: OSRSUtilities
  resource: OSRSUtilities
  public-client: true
  principal-attribute: preferred_username
